runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scalling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:CKLWB8+7QFhBxlMv+e1pmdJ/vG5g6pyfqx09iIjMKrY=
  APP_NAME: "GCP App - Sakukode"

  LOG_LEVEL: debug
