steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ["-c", "gcloud config set app/cloud_build_timeout 3600", "gcloud app deploy -q --promote -v=$BUILD_ID", "--project=$PROJECT_ID"]
  entrypoint: "bash"
  timeout: "3600s"
  